// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String formattedHumdiditySensor;
String formattedOutHumdiditySensor;
String formattedPressureSensor;
CloudTemperatureSensor formattedC;
CloudTemperatureSensor formattedOutC;

void initProperties(){

  ArduinoCloud.addProperty(formattedHumdiditySensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(formattedOutHumdiditySensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(formattedPressureSensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(formattedC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(formattedOutC, READ, ON_CHANGE, NULL);


  ArduinoCloud.updateCertificate(CERT_AUTHORITY, CERT_SERIAL, CERT_NOT_BEFORE, CERT_NOT_AFTER, CERT_SIGNATURE_RS);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
